### ISSUE TITLE
openBinaryFile: does not exist when using alias

### ISSUE THREAD

**Issue by gabrielziegler3** [dalibo/pandocker#111]
I get the exception: 

`pandoc: "filename": openBinaryFile: does not exist (No such file or directory)`

when using the alias `pandoc` described in the readme.

`pandoc file.md`

I put ```alias pandoc="docker run --rm -u `id -u`:`id -g` -v `pwd`:/pandoc dalibo/pandocker"` in my `~/.zshrc``` and the alias always give me this exception.

The exception happens in both ZSH and Bash for me.
I am using Manjaro 5.2.11 and ZSH 5.7.1

**Comment by daamien** [comment]
Hi @gabrielziegler3 !

Thanks for this feedback. 

At first grlance, it looks like docker did not mount the volume and therefore pandoc cannot see you file. There might be several reasons for that, here a few ideas to try:

* Do you have SELinux enforced on you system ? If so, can you set the policy to `permissive` ?
* Can you add the `--privileged` option to the alias ?

**Comment by daamien** [comment]
Hi @gabrielziegler3 !

Any update on this ?

**Comment by gabrielziegler3** [comment]
I'm not aware if I have SElinux enforced in my system, I have never used it. Can it be enforced in my system even though I haven't configured it?

I can mount volumes using the very same command when using other docker images.

**Comment by gabrielziegler3** [comment]
Indeed adding `--privileged` to my alias command worked! I am sorry for the confusion, I wasn't aware of SELinux.

Thank you!


EDIT:

Do NOT use double quotes for your aliases as this will make `pwd` not work properly. Instead, stick with the single quotes.
https://unix.stackexchange.com/a/303675/279215

**Comment by daamien** [comment]
@gabrielziegler3 : This is a very common problem. I added a FAQ for this kind of errors.

Have a nice day !

**Comment by gabrielziegler3** [comment]
Hey, I've just faced the same issue again even tho I'm using the `--privileged` option.
The problem now is in the `pwd` step in the alias I was using which would always output the path where my alias script was placed.

Changing the alias from ```docker run --privileged --rm -u 1000:1000 -v `pwd`:/pandoc dalibo/pandocker``` to ```docker run --privileged --rm -u 1000:1000 -v $(pwd):/pandoc dalibo/pandocker``` did the trick for me, because now the pwd command is ran in the current directory I am calling the alias. 

Maybe this one is best to use as an alias for pandocker :)
