### ISSUE TITLE
Panflute vs. Pandoc 2.10

### ISSUE THREAD

**Issue by daamien** [dalibo/pandocker#184]
There's currently a conflict between panflute and pandoc 2.10

https://github.com/sergiocorreia/panflute/issues/142

This means we will probably have to downgrade to 2.9

**Comment by CircleCode** [comment]
if I understand it correctly, sergiocorreia/panflute#142 is now resolved (see https://github.com/sergiocorreia/panflute/issues/142#issuecomment-724383120), and latest panflute requires pandoc 2.11 at least.
If i am right, it is time to update pandoc and to close this issue :-)

**Comment by daamien** [comment]
@CircleCode:  thanks for the update ! 

I'll be working on this in the forthcoming days

**Comment by daamien** [comment]
Closed by #190
