### ISSUE TITLE
pandoc-crossref complains about version mismatch

### ISSUE THREAD

**Issue by colindean** [dalibo/pandocker#207]
## Describe the bug

When using Pandocker 21.02, `pandoc-crossref` complains about the pandoc version mismatch:

```
WARNING: pandoc-crossref was compiled with pandoc 2.11.3.2 but is being run through 2.11.3. This is not supported. Strange things may (and likely will) happen silently.
```

## Steps To Reproduce

Run pandocker with `--filter pandoc-crossref` and it'll come out.

## Expected Behavior

No scary error messages that likely don't actually output differently and maybe the result of an imprecise/too precise version number check.

## Additional context

It looks like pandoc-crossref v0.3.9.1 was compiled against pandoc v2.11.4. pandoc-crossref complaining when it's not compiled against a precise version is frustrating.

**Comment by daamien** [comment]
Hi @colindean 

Thanks for the reports. 

* Pandoc 2.12 was released yesterday. I'm waiting for a new release of pandoc-crossref to update
* I will add a CI test for this WARNING message and detect the problem earlier
* There are 2 others issues with the 21.02 version so it is likely will produce a version 21.03 soon
