### ISSUE TITLE
Add mermaid support 

### ISSUE THREAD

**Issue by daamien** [dalibo/pandocker#43]

**Comment by the-nicolas** [comment]
Good job, just start to open an issue for that. Would be great to have that!

It would blow up the docker size, but it would also support all other kinds of nodejs/chromium filters in the future...

**Comment by Krysztophe** [comment]
Just a word: I'd really love to see this

**Comment by daamien** [comment]
This should work:

https://github.com/mermaidjs/mermaid.cli/pull/32#issuecomment-381150431

**Comment by daamien** [comment]
I'm closing this because mermaid-cli now has a docker image

https://github.com/mermaid-js/mermaid-cli
