### ISSUE TITLE
Test Tinytex

### ISSUE THREAD

**Issue by daamien** [dalibo/pandocker#67]
https://yihui.name/tinytex/

**Comment by agusmba** [comment]
Thanks for the pointer!
I have my own very simple docker image without latex support, because I prioritized image size (~70MB compressed) over feature completeness. However if a basic latex for pandoc can be added in the ~200MB range it would be great.
Please let us know what you find.

**Comment by agusmba** [comment]
I tested it a little bit, my first attempt didn't work due to perl issues. My second attempt got me a working image with only 200MB additional size

**Comment by daamien** [comment]
hi @agusmba !

Thanks a lot for your feedback, it's helpful. The current compressed size of our image is currently 264MB so I was to hoping we could go far below 200MB...  Otherwise It does not seems worth the effort. 

I've done recent research with alpine and the texlive package manager, based on various existing images (links below) but all my experiences failed and I found that tlmgr is complex and not reliable...

I'm leaving this issue opened but putting on "low priority".

https://github.com/dc-uba/docker-alpine-texlive/blob/develop/Dockerfile
https://github.com/blang/latex-docker

**Comment by agusmba** [comment]
Hi @daamien !

My pleasure.
After trying several different approaches I opted to leverage the fact that TinyTeX is portable, so I built it on a temporal R image, and copied the installed artifacts on top of my working pandoc image (multi-stage docker build).

I think this will add the least amount of space to your final pandoc image, although it is a bit time consuming identifying all the missing latex packages and adding them to the build. I had to iterate multiple times, I probably could have saved time if I was more fluent with latex...

Anyway, you can check the result out [here](https://github.com/agusmba/pandocomatic-docker/blob/master/tex/Dockerfile) if you're interested.

**Comment by daamien** [comment]
I'm closing this because the issue #165 will solve some problems we add with `tmlgr`...
