### ISSUE TITLE
Can't convert Markdown to PDF

### ISSUE THREAD

**Issue by liloumuloup** [dalibo/pandocker#73]
Hello,

I can't convert any Markdown document to PDF.

I'm using the last image available on Dockehub + podman on the last Fedora release

Here are the commands i tried : 

```
podman run --privileged  --rm -u `id -u`:`id -g` -v `pwd`:/pandoc dalibo/pandocker lol.md -o lol.pdf
Error producing PDF.
! Package inputenc Error: Unicode char 🐛 (U+1F41B)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.75   🐛

Try running pandoc with --pdf-engine=xelatex.
```

```
podman run --privileged  --rm -u `id -u`:`id -g` -v `pwd`:/pandoc dalibo/pandocker --pdf-engine=xelatex --template=eisvogel lol.md -o lol.pdf 
Could not find data file templates/eisvogel.latex
```

```
podman run --privileged  --rm -u `id -u`:`id -g` -v `pwd`:/pandoc dalibo/pandocker --pdf-engine=xelatex lol.md -o lol.pdf 
[WARNING] Missing character: There is no 🐛 in font [lmroman10-regular]:mapping=tex-text;!
[WARNING] Missing character: There is no 🔒 in font [lmroman10-regular]:mapping=tex-text;!
[WARNING] Missing character: There is no 🚀 in font [lmroman10-regular]:mapping=tex-text;!
[WARNING] Missing character: There is no 👷 in font [lmroman10-regular]:mapping=tex-text;!
[WARNING] Missing character: There is no 💚 in font [lmroman10-regular]:mapping=tex-text;!
[WARNING] Missing character: There is no 📝 in font [lmroman10-regular]:mapping=tex-text;!
[WARNING] Missing character: There is no 📝 in font [lmroman10-regular]:mapping=tex-text;!
[WARNING] Missing character: There is no 🏗 in font [lmroman10-regular]:mapping=tex-text;!
[WARNING] Missing character: There is no ✨ in font [lmroman10-regular]:mapping=tex-text;!
[WARNING] Missing character: There is no 🚀 in font [lmroman10-regular]:mapping=tex-text;!
[WARNING] Missing character: There is no 🐛 in font [lmroman10-regular]:mapping=tex-text;!
[WARNING] Missing character: There is no 🔧 in font [lmroman10-regular]:mapping=tex-text;!
[WARNING] Missing character: There is no 🔒 in font [lmroman10-regular]:mapping=tex-text;!
[WARNING] Missing character: There is no 🔒 in font [lmroman10-regular]:mapping=tex-text;!
[WARNING] Missing character: There is no 👽 in font [lmroman10-regular]:mapping=tex-text;!
[WARNING] Missing character: There is no 👽 in font [lmroman10-regular]:mapping=tex-text;!
[WARNING] Missing character: There is no ✨ in font [lmroman10-regular]:mapping=tex-text;!
[WARNING] Missing character: There is no ✨ in font [lmroman10-regular]:mapping=tex-text;!
[WARNING] Missing character: There is no 💚 in font [lmroman10-regular]:mapping=tex-text;!
[WARNING] Missing character: There is no 👷 in font [lmroman10-regular]:mapping=tex-text;!
```

To be more precise, the conversion Markdown to HTML works like a charm using this command : 
```
podman run --privileged  --rm -u `id -u`:`id -g` -v `pwd`:/pandoc dalibo/pandocker lol.md -o lol.html
```

Did i miss something ?

Best regards.

**Comment by liloumuloup** [comment]
Ok, after a few more texts, i think that the problem is that the default font (lmroman10-regular) doesn't support emojis.

I tried to use another one included in the Texlive package but it doesn't work. Is there anyway to enable emojis with pandocker ?

**Comment by daamien** [comment]
I confirm there's no support for emojis at the moment. 😞 

I'll have a look into it in a few days and let you know 

Thanks for your interest in pandocker

**Comment by daamien** [comment]
related : https://github.com/alecjacobson/coloremoji.sty

**Comment by daamien** [comment]
https://github.com/mreq/xelatex-emoji

**Comment by liloumuloup** [comment]
Thanks a lot for your researchs. 

It might be simpler with the Google Noto fonts. What dou you think about it ? 😃 

https://www.google.com/get/noto/

There are several fonts, one of them containing emojis.

Best regards.

**Comment by daamien** [comment]
@liloumuloup : I tried the noto package here https://ctan.org/tex-archive/fonts/noto

It seems to me that the CTAN package does not include the `noto-emoji` style.

Anyway I'm getting the same error:
```
[WARNING] Missing character: There is no 🌎 infont [NotoSerif-Regular.otf]/OT:script=latn
```

By the way noto is a nice font, i'll add it to docker image anyway 😄

**Comment by daamien** [comment]
@liloumuloup : ok it seems to work fine with `xelatex-emoji` and the `twemoji` collection.

Can you pull the `dalibo/pandocker:add_emojis` tag and add the 2 packages below to your template

```
\usepackage{xltxtra}
\usepackage{xelatexemoji}
```

If you're using the default template,  add the packages with the `header-includes` option in the front matter, like this ;

```markdown
---
title: Hello, 🌍
header-includes: |
    \usepackage{xltxtra}
    \usepackage{xelatexemoji}
---

😀

```

If your souce file is named `lol.md` you should be able to  produce a lol.pdf file with:

```
docker run --rm --volume=`pwd`:/pandoc dalibo/pandocker:add_emojis --pdf-engine=xelatex lol.md -o lol.pdf
```

**Comment by liloumuloup** [comment]
Hello @daamien ,

Thanks a lot for your help. I managed to convert my document after removing the emoji 🏗 .

Here is the exact error : 
```
podman run --rm --privileged  --volume=`pwd`:/pandoc dalibo/pandocker:add_emojis --pdf-engine=xelatex magicienletter.md -o magicienletter.pdf
Error producing PDF.
! LaTeX Error: File `images/1f3d7' not found.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.99   🏗
```

It's not a problem anymore for me, i'll edit my documents without that specific emoji.

Will that new feature be part of the February release ?

**Comment by daamien** [comment]
@liloumuloup 

Sorry about that. I loaded a very old version of the [twemoji](https://github.com/twitter/twemoji) library.

Can you update your image with `docker pull dalibo/pandocker:add_emojis` and check if all your emojis are supported now ?

This feature is schedule for the next release in a few weeks, until then you can use the `add_emojis` tag

Regards

**Comment by liloumuloup** [comment]
Hello @daamien ,

Thank you for the update and sorry for the delay.

I just tried and there is and there is an improvement ! 👍 

The thermometer works now but i still have the error with the others.

**Comment by daamien** [comment]
Hi !

Can you give us the list of emojis that does not work for you ?

**Comment by liloumuloup** [comment]
Hello @daamien ,

Based on the website http://getemoji.com/, I created a specific file to test emojis rendering.

I attached this file and the result of my tests to this message.
[Markdown source test_emojis.md.txt](https://github.com/dalibo/pandocker/files/2760152/test_emojis.md.txt)
[Error output test_emojis_output.txt](https://github.com/dalibo/pandocker/files/2760143/test_emojis_output.txt)

(The file `test_emojis.md.txt` needs to be downloaded and renamed `test_emojis.md`)

**Comment by daamien** [comment]
I'm sorry I don't have the time to check every emoji character. Unless you're able to give me precise list of missing symbols, I can't help you more. 

By the way, your second file contains data about your employer, you probably want to remove it from github;

**Comment by daamien** [comment]
Are you sure that you defined correctly the `header-includes` option ? 

It should be declared like this :

```
header-includes: |
    \usepackage{xltxtra}
    \usepackage{xelatexemoji}
```

**Comment by commjoen** [comment]
First of all: thank you very much for the awesome pandocker container!

And sorry to respond to an older issue... but: I followed your lead for https://github.com/OWASP/owasp-masvs/tree/automation and tried to use:
````
docker run --rm -u `id -u`:`id -g` -v `pwd`:/pandoc dalibo/pandocker --pdf-engine=xelatex --template=/pandoc/Document/template.yml Document/*.md -o test.pdf
````
while being at the root of the folder, with your header include example posted here. However, I ended up with : 
````
[WARNING] Could not fetch resource 'images/OWASP_logo.png': replacing image with description
[WARNING] Could not fetch resource 'images/OWASP_logo.png': replacing image with description
[WARNING] Could not fetch resource 'images/CC-license.png': replacing image with description
[WARNING] Could not fetch resource 'images/NowSecure_logo.png': replacing image with description
[WARNING] Could not fetch resource 'images/Randorisec_logo.png': replacing image with description
[WARNING] Could not fetch resource 'images/masvs-levels-new.jpg': replacing image with description
Error producing PDF.
! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.1 -
````

What am I doing wrong? Can you please help me out?

**Comment by daamien** [comment]
Hi @commjoen,

This looks like a basic problem of wrong ressource path. Your markdown documents are including images with a path that is relative to the document directory ( `images/xxx.png` ) but you are launching pandoc from the directory above (the root of the project) and pandoc can't find the images. 

You have 3 different ways of fixing this :

1- Launch the pandoc command inside the `Document` folder

2- Change all images path to `Document/images/xxxx.png` in all the markdown files

3- Tell pandoc where to find the images with the following option `--resource-path=.:Document`

Personnally I like to use the third one, but that's up to you.

**Comment by commjoen** [comment]
Thank you very much!
Running 
```
 docker run --rm -u `id -u`:`id -g` -v `pwd`:/pandoc dalibo/pandocker --pdf-engine=xelatex --template=eisvogel  --resource-path=.:Document Document/*.md -o test.pdf
```
gives
```
[WARNING] Missing character: There is no ‑ (U+2011) in font [SourceSansPro-Regular.otf]/OT:script=
[WARNING] Missing character: There is no ‑ (U+2011) in font [SourceSansPro-Regular.otf]/OT:script=
```

Which leaves me to , I guess, modifying the template and include 
```
header-includes: |
    \usepackage{xltxtra}
    \usepackage{xelatexemoji}
```

**Comment by commjoen** [comment]
Thanks!

**Comment by arvenil** [comment]
I want to cry 😭
```
docker run      --rm -u `id -u`:`id -g` \
                                --volume `pwd`:/pandoc dalibo/pandocker:latest-full \
                                --pdf-engine=xelatex \
                                --css=docs/main.css \
                                --output test5.pdf \
                                header-includes.yaml \
                                README.md
[WARNING] Missing character: There is no 🛼 (U+1F6FC) in font Noto Sans Regular/OT:script=latn;langu
[WARNING] Missing character: There is no 形 (U+5F62) in font Noto Sans Reular/OT:script=latn;langu
```

It's also not possible to add --css since wkhtmltopdf is not installed :(
