### ISSUE TITLE
Prepare for Buster

### ISSUE THREAD

**Issue by daamien** [dalibo/pandocker#99]

**Comment by commjoen** [comment]
Hi there! It seems we need Buster and the new Texlive base in order to be able to generate Persian documents as well. Do you have any status/planning updates on this?

**Comment by gpmontt** [comment]
Hi every one, I fork your project and I'm trying to implement the github-actions [velocitymob/pandocker](https://github.com/velocitymob/pandocker/tree/0c55c14401fd7a18eae11b1a6813b9a415b7972d)
I the buster version I was able to include the fontawesome5  only with the texlive-fonts-extra, the option with tlmgr gave me a error.
nice Job I want to take part of your project 👍 it is possible :) .

**Comment by commjoen** [comment]
Very interested in your results @gpmontt ! Where can i find the result of your container? I would love to take it for a spin for our project (https://github.com/OWASP/owasp-masvs and https://github.com/OWASP/owasp-mstg)

**Comment by daamien** [comment]
Hi @gpmontt !

Thanks for you message, we're intresested by the Github Actions. Can you open a separate PR with your work and we'll see about to integrate it. 

Same things with the fontawesome patch.

Regards

**Comment by daamien** [comment]
2nd attempt #172
